name: Check & Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies  
        run: npm install -g pnpm && pnpm install

      - name: Test
        run: pnpm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    name: Deploy
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies  
        run: npm install -g pnpm && pnpm install

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}